#数据库连接信息
spring:
  datasource:
    #url: jdbc:mysql:///robot #5.x
    url: jdbc:mysql://10.112.34.131:3306/robot?characterEncoding=utf8 & useSSL=false & serverTimezone=UTC & rewriteBatchedStatements=true
    #data-username: root #不要使用IDEA自动提示的
    username: root
    #data-password: root
    password: root
    #driverClassName: com.mysql.jdbc.Driver #5.x
    driverClassName: com.mysql.cj.jdbc.Driver #8.x
    #driver-class-name: com.mysql.jdbc.Driver 用这个会报异常
#别名扫描
mybatis:
  type-aliases-package: edu.bupt.robot.pojo
#服务端口
server:
  port: 10086